apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rahul-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/SHArahul/demo-ArgoCD.git
    targetRevision: HEAD
    path: k8s-manifest
  destination:
    server: https://kubernetes.default.svc
    namespace: demo-rahul
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Timeout=30s # Sets the sync timeout to 300 seconds
